#!/usr/bin/env bash
# One-command bring-up of the self-hosted Brain/Out online backend.
#
# Ties together everything that was previously hand-assembled across the session
# and docs/OnlinePlatformLocal.md: the upstream anthill-dev stack, the brainout
# registration, the scope/FK/market fixes, the JRE-17 controller image, the
# game-server provisioning, the deployment staging and the economy seed.
#
# Idempotent — safe to re-run. Works for a local box (PUBLIC_HOST=localhost) and
# for a real server (PUBLIC_HOST=<public ip/domain>).
#
# Prereqs on the target:
#   * docker + docker compose, git, bash, and python3 (Ubuntu has it; on the
#     Windows dev box `python` is picked up automatically)
#   * the server payload built:  ./gradlew server:dist make_data   (bin/server)
#
# Usage:
#   PUBLIC_HOST=203.0.113.10 ./deploy/anthill/deploy.sh
#   ./deploy/anthill/deploy.sh                 # local, PUBLIC_HOST=localhost
set -euo pipefail

# ----- config (override via env) -------------------------------------------
HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"

PUBLIC_HOST="${PUBLIC_HOST:-localhost}"          # what clients connect to
ANTHILL_REPO="${ANTHILL_REPO:-https://github.com/anthill-platform/anthill-dev.git}"
ANTHILL_DIR="${ANTHILL_DIR:-$REPO/../anthill-dev/dev}"   # the upstream stack's dev/
MYSQL_CONTAINER="${MYSQL_CONTAINER:-mysql}"
MYSQL_ROOT_PW="${MYSQL_ROOT_PW:-Root123}"
GAMESPACE_ID="${GAMESPACE_ID:-1}"
GAME="${GAME:-brainout}"
VERSION="${VERSION:-valpha2}"
DEPLOYMENT_ID="${DEPLOYMENT_ID:-1}"
CONTROLLER_IMAGE="${CONTROLLER_IMAGE:-brainout/anthill-game-controller:jre17}"
PORTS_FROM="${PORTS_FROM:-38000}"                # narrow pool -> easy firewalling
PORTS_TO="${PORTS_TO:-38020}"

# pick an interpreter that actually runs — on Windows `python3` may be the
# non-functional Microsoft Store alias, so verify each candidate executes
PYTHON=""
for _py in python3 python; do
  if command -v "$_py" >/dev/null 2>&1 && "$_py" -c "import sys" >/dev/null 2>&1; then
    PYTHON="$_py"; break
  fi
done
export MYSQL_CONTAINER MYSQL_ROOT_PW GAMESPACE_ID GAME VERSION DEPLOYMENT_ID

step() { echo; echo "==== $* ===="; }
# run SQL, keep real errors visible, drop only the known container noise
myq() {
  { echo "SET NAMES utf8mb4;"; cat; } \
    | docker exec -i "$MYSQL_CONTAINER" mysql -uroot -p"$MYSQL_ROOT_PW" "$1" 2>&1 \
    | grep -vE "Using a password on the command line|Found option without preceding group" || true
}
wait_for() { # wait_for "<desc>" <cmd...>
  local desc="$1"; shift; local n=90
  until "$@" >/dev/null 2>&1; do
    n=$((n-1)); [ $n -le 0 ] && { echo "timed out waiting for: $desc"; return 1; }
    sleep 3
  done
}
db_exists()    { docker exec -i "$MYSQL_CONTAINER" mysql -uroot -p"$MYSQL_ROOT_PW" -N -e \
                 "SELECT 1 FROM information_schema.schemata WHERE schema_name='$1'" 2>/dev/null | grep -q 1; }
table_exists() { docker exec -i "$MYSQL_CONTAINER" mysql -uroot -p"$MYSQL_ROOT_PW" -N -e \
                 "SELECT 1 FROM information_schema.tables WHERE table_schema='$1' AND table_name='$2'" 2>/dev/null | grep -q 1; }

dc() { ( cd "$ANTHILL_DIR" && docker compose "$@" ); }

# ----- 0. prechecks ---------------------------------------------------------
step "0. prechecks"
command -v docker >/dev/null || { echo "docker not found"; exit 1; }
[ -n "$PYTHON" ] || { echo "python3/python not found"; exit 1; }
[ -f "$REPO/bin/server/brainout-server.jar" ] || { echo "missing bin/server/brainout-server.jar — run ./gradlew server:dist"; exit 1; }
[ -d "$REPO/bin/server/packages" ] || { echo "missing bin/server/packages — run ./gradlew make_data"; exit 1; }
echo "PUBLIC_HOST=$PUBLIC_HOST  ANTHILL_DIR=$ANTHILL_DIR  ports=$PORTS_FROM-$PORTS_TO"

# ----- 1. upstream stack ----------------------------------------------------
step "1. anthill-dev stack"
if [ ! -d "$ANTHILL_DIR" ]; then
  echo "cloning $ANTHILL_REPO"
  git clone "$ANTHILL_REPO" "$(dirname "$ANTHILL_DIR")"
fi
# CRLF in *.sh breaks keygen when the repo was cloned on Windows
find "$ANTHILL_DIR/.." -name '*.sh' -not -path '*/.git/*' -exec sed -i 's/\r$//' {} + 2>/dev/null || true

# generated override: JRE-17 controller image + public gs_host + narrowed port pool
cat > "$ANTHILL_DIR/docker-compose.override.yml" <<YAML
# generated by deploy/anthill/deploy.sh — do not edit by hand
services:
  anthill_game_controller:
    image: $CONTROLLER_IMAGE
    environment:
      gs_host: "$PUBLIC_HOST"
      ports_pool_from: $PORTS_FROM
      ports_pool_to: $PORTS_TO
YAML

step "1b. controller image ($CONTROLLER_IMAGE)"
docker build -f "$HERE/controller.Dockerfile" -t "$CONTROLLER_IMAGE" "$HERE"

step "1c. build keygen + up"
dc build anthill_keygen
dc up -d
wait_for "keys"  test -f "$ANTHILL_DIR/keys/public/anthill.pub"
wait_for "mysql" bash -c "docker exec $MYSQL_CONTAINER mysqladmin -uroot -p$MYSQL_ROOT_PW ping 2>/dev/null | grep -q alive"
wait_for "dev_login"   db_exists dev_login
wait_for "dev_store"   table_exists dev_store stores
wait_for "dev_game"    db_exists dev_game
echo "stack up, seed schemas present"

# ----- 2. register brainout -------------------------------------------------
step "2. register brainout (app / version / gamespace / scopes)"
myq dev_environment <<SQL
INSERT INTO applications (application_name, application_title, min_api)
  SELECT '$GAME','Brain/Out','0.2' FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM applications WHERE application_name='$GAME');
INSERT INTO application_versions (application_id, version_name, version_environment)
  SELECT application_id, '$VERSION', 1 FROM applications WHERE application_name='$GAME'
  AND NOT EXISTS (SELECT 1 FROM application_versions av JOIN applications a ON av.application_id=a.application_id
                  WHERE a.application_name='$GAME' AND av.version_name='$VERSION');
SQL
myq dev_login <<SQL
INSERT INTO gamespace_aliases (gamespace_name, gamespace_id)
  SELECT '$GAME:desktop', $GAMESPACE_ID FROM DUAL
  WHERE NOT EXISTS (SELECT 1 FROM gamespace_aliases WHERE gamespace_name='$GAME:desktop');
-- widen the gamespace scopes to cover ClientConstants.Scopes.SCOPES (else login loops)
UPDATE gamespace SET gamespace_scopes=
 'profile,profile_write,game,game_root,game_mod,game_editor,message_listen,store,group,static_upload,party,party_create,report_upload,blog,game_ban,market,event,exec_func_call'
 WHERE gamespace_id=$GAMESPACE_ID;
SQL

# ----- 3. store FK fix ------------------------------------------------------
step "3. store FK fix (campaigns/campaign_items/orders)"
if ! table_exists dev_store orders; then
  SIMG=anthillplatform/anthill-store:latest
  SQLDIR=/usr/local/lib/python3.7/site-packages/anthill/store/sql
  for f in campaigns campaign_items orders; do
    docker run --rm --entrypoint sh "$SIMG" -c "cat $SQLDIR/$f.sql" \
      | docker exec -i "$MYSQL_CONTAINER" mysql -uroot -p"$MYSQL_ROOT_PW" dev_store 2>/dev/null || true
  done
  docker restart anthill_store >/dev/null
  echo "created missing store tables; restarted store"
else
  echo "orders table already present — skipping"
fi

# ----- 4. discovery: market stub + public external addresses ---------------
step "4. discovery (market stub + external host -> $PUBLIC_HOST)"
DISCOVERY_JSON="$ANTHILL_DIR/discovery/discovery-services.json"
PUBLIC_HOST="$PUBLIC_HOST" "$PYTHON" - "$DISCOVERY_JSON" <<'PY'
import json, os, sys, re
path = sys.argv[1]; host = os.environ["PUBLIC_HOST"]
d = json.load(open(path, encoding="utf-8")); svc = d["services"]
# the game's DISCOVER list needs a market service anthill-dev lacks -> stub to store
if "market" not in svc and "store" in svc:
    svc["market"] = dict(svc["store"])
# rewrite every external URL host to the public host, keep the port
for s in svc.values():
    ext = s.get("external")
    if ext:
        s["external"] = re.sub(r"http://[^:/]+:", "http://%s:" % host, ext)
json.dump(d, open(path, "w", encoding="utf-8"), indent=4)
print("discovery services:", ", ".join(sorted(svc)))
PY
docker restart anthill_discovery >/dev/null

# env discovery location must be reachable by clients too
myq dev_environment <<SQL
UPDATE environments SET environment_discovery='http://$PUBLIC_HOST:9502' WHERE environment_id=1;
SQL

# ----- 5. provision game servers + server dev account ----------------------
step "5. provision game servers (free + lobby) + server dev account"
wait_for "dev_game.game_servers" table_exists dev_game game_servers
bash "$HERE/provision.sh"

# ----- 6. stage the deployment ---------------------------------------------
step "6. stage server deployment"
STAGE="$ANTHILL_DIR/data/game-controller/binaries/runtime/$GAME/$VERSION/$DEPLOYMENT_ID"
bash "$HERE/build-deployment.sh" "$STAGE"

# ----- 7. economy seed ------------------------------------------------------
step "7. seed economy (currencies + starter store catalog)"
bash "$HERE/seed-economy.sh"

# ----- 8. recreate controller with the generated override ------------------
step "8. recreate controller"
dc up -d --no-build --force-recreate anthill_game_controller
wait_for "controller<->master" bash -c \
  "docker logs anthill_game_controller --since 120s 2>&1 | grep -q 'Connected to Game Master'"

# ----- 9. verify ------------------------------------------------------------
step "9. verify"
echo -n "env  -> "; curl -s -m 8 "http://$PUBLIC_HOST:9503/$GAME/$VERSION" || true; echo
echo -n "disc -> "; curl -s -m 8 "http://$PUBLIC_HOST:9502/services/login,game,market" -o /dev/null -w "%{http_code}" || true; echo

cat <<DONE

Backend is up for $GAME:$VERSION on $PUBLIC_HOST.
  * desktop client:  java -Dbrainout.env_service=http://$PUBLIC_HOST:9503 -jar bin/client/brainout-desktop.jar --unsafe
  * android APK:     ./gradlew :android:assembleDebug -PwithAndroid -PbrainoutOnline=true -PbrainoutEnvService=http://$PUBLIC_HOST:9503

If PUBLIC_HOST is a real server, open the firewall:
  * TCP 9500-9518            (anthill services)
  * TCP+UDP $PORTS_FROM-$PORTS_TO   (game rooms — kryonet needs UDP too)
DONE
